const Main = () =>{
    return(
        <>
        <main className="main">
Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione, explicabo non beatae ea quos repudiandae illum nostrum voluptatum officiis velit odit nam sed quae consectetur alias quam debitis labore doloremque est accusamus? Adipisci rem tempore deserunt voluptatum corporis repellat, eveniet debitis qui aperiam veniam nihil, repudiandae accusamus minima voluptate. Magni quibusdam vel architecto, asperiores eius beatae ut, enim rem veniam eum voluptas nobis non dolorem aspernatur odit. Atque odio voluptate impedit fugit quis at quasi nulla dolore ratione doloremque numquam, rerum odit assumenda quo, dolor rem a reiciendis porro aliquid voluptas quos alias. Aliquid inventore obcaecati suscipit alias eaque consequatur facere quod id quae error, quibusdam aut culpa? Asperiores expedita deleniti neque fuga, quae unde, minus vel enim dolores dolore quaerat inventore sunt nulla dolorem quas sed dignissimos vero magni. Illo, exercitationem? Modi illo aliquid est vero, ipsa omnis fugiat debitis perspiciatis eligendi alias mollitia in rerum esse blanditiis incidunt! Libero aperiam esse quidem iusto quae voluptatibus expedita voluptates debitis laborum. Temporibus rem a consequatur provident repudiandae nostrum sunt ducimus magnam dolorum. Sit quod repellendus saepe excepturi quidem veritatis, neque laborum mollitia asperiores a voluptate rerum harum, perspiciatis velit? Et, culpa fugiat obcaecati illum ex ipsum incidunt tempore voluptates veritatis maxime veniam quo aspernatur. Ex, at consectetur. Voluptate aspernatur cumque suscipit aperiam porro fugit, ab dolores tempora nesciunt facilis dolor cupiditate. Voluptas rem obcaecati necessitatibus animi dolor ex. Deleniti iure aliquam doloribus quidem possimus temporibus minima debitis impedit, cumque fugiat officia, quam nostrum accusantium hic delectus minus ea saepe ex fugit inventore totam quos corporis repellat architecto! Natus minus repellat veniam veritatis temporibus laborum dolores. Autem magnam commodi voluptatem libero nihil inventore neque fugit consequuntur! Tenetur est aspernatur fugiat atque, quod earum aliquid provident laboriosam accusamus rem maiores in totam ex aperiam temporibus perspiciatis ullam corporis cupiditate explicabo beatae sapiente eaque consequuntur. Magnam corrupti consectetur at nesciunt. Provident, repellendus voluptate? Ullam sit reprehenderit atque rem obcaecati incidunt ex aliquid totam architecto delectus et ipsam molestias reiciendis, ipsa a, enim quidem nobis. Id ullam beatae quidem quisquam deleniti qui corporis veritatis dolore natus impedit omnis unde ipsa, officiis, fugiat et maiores ab adipisci ratione non odio dolorum. Sapiente, omnis quaerat dolorum nam incidunt eligendi. Ipsam est veritatis error ex, maiores eum laboriosam natus aliquid amet officia, corporis nesciunt id ab voluptatem quasi consequuntur, doloribus quibusdam ea velit. Et corrupti cupiditate omnis? Architecto, ab. Ipsa tempora est nihil. Cum repellat at fugiat.
        </main>
        </>
    )
}
export default Main